# Generated by Django 3.1.1 on 2020-09-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolo_users', '0002_auto_20200909_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
