# Generated by Django 3.1.1 on 2020-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo_users', '0003_auto_20200910_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='acronym',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
